<?php


namespace App\Repositories;


use App\DbModels\Attachment;
use App\DbModels\ServiceRequest;
use App\DbModels\ServiceRequestMessage;
use App\Events\ServiceRequest\ServiceRequestCreatedEvent;
use App\Events\ServiceRequest\ServiceRequestUpdatedEvent;
use App\Repositories\Contracts\AttachmentRepository;
use App\Repositories\Contracts\ServiceRequestMessageRepository;
use App\Repositories\Contracts\ServiceRequestRepository;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class EloquentServiceRequestRepository extends EloquentBaseRepository implements ServiceRequestRepository
{
    /**
     * @inheritDoc
     */
    public function save(array $data): \ArrayAccess
    {
        DB::beginTransaction();
        $serviceRequest = parent::save($data);

        if (isset($data['attachmentIds'])) {
            $attachmentRepository = app(AttachmentRepository::class);

            foreach ($data['attachmentIds'] as $attachment) {
                $attachment = $attachmentRepository->findOne($attachment);
                if ($attachment instanceof Attachment) {
                    $attachmentRepository->updateResourceId($attachment, $serviceRequest->id);
                }
            }

            unset($data['attachmentIds']);
        }

        DB::commit();

        // fire service request created event
        event(new ServiceRequestCreatedEvent($serviceRequest, $this->generateEventOptionsForModel()));

        return $serviceRequest;
    }

    /**
     * @inheritDoc
     */
    public function update(\ArrayAccess $model, array $data): \ArrayAccess
    {
        // save text in ServiceRequestMessage
        if (isset($data['feedbackText'])) {
            $serviceRequestMessageRepository = app(ServiceRequestMessageRepository::class);
            $serviceRequestMessageRepository->saveByServiceRequest($model, $data['feedbackText'], ServiceRequestMessage::TYPE_FEEDBACK);
            unset($data['feedbackText']);
        }

        if (isset($data['status']) ) {
            if ($data['status'] == ServiceRequest::STATUS_RESOLVED) {
                $data['resolvedAt'] = Carbon::now();
            }
        }

        $serviceRequest = parent::update($model, $data);

        event(new ServiceRequestUpdatedEvent($serviceRequest, $this->generateEventOptionsForModel()));

        return $serviceRequest;
    }

    /**
     * @inheritDoc
     */
    public function findBy(array $searchCriteria = [], $withTrashed = false)
    {
        $queryBuilder = $this->model;

        if (isset($searchCriteria['endDate'])) {
            $queryBuilder = $queryBuilder->whereDate('created_at', '<=', Carbon::parse($searchCriteria['endDate']));
            unset($searchCriteria['endDate']);
        }

        if (isset($searchCriteria['startDate'])) {
            $queryBuilder = $queryBuilder->whereDate('created_at', '>=', Carbon::parse($searchCriteria['startDate']));
            unset($searchCriteria['startDate']);
        }

        $searchCriteria['eagerLoad'] = ['sr.createdByUser' => 'createdByUser', 'sr.user' => 'user', 'sr.category' => 'serviceRequestCategory', 'sr.serviceRequestMessages' => 'serviceRequestMessages', 'sr.unit' => 'unit', 'unit.tower' => 'unit.tower', 'sr.logs' => 'logs', 'srLog.user' => 'logs.user', 'user.roles' => 'user.userRoles', 'sr.photos' => 'serviceRequestPhotos'];

        $queryBuilder = $queryBuilder->where(function ($query) use ($searchCriteria) {
            $this->applySearchCriteriaInQueryBuilder($query, $searchCriteria);
        });

        $limit = !empty($searchCriteria['per_page']) ? (int)$searchCriteria['per_page'] : 15;
        $orderBy = !empty($searchCriteria['order_by']) ? $searchCriteria['order_by'] : 'id';
        $orderDirection = !empty($searchCriteria['order_direction']) ? $searchCriteria['order_direction'] : 'desc';
        $queryBuilder->orderBy($orderBy, $orderDirection);

        if (empty($searchCriteria['withOutPagination'])) {
            return $queryBuilder->paginate($limit);
        } else {
            return $queryBuilder->get();
        }
    }

    /**
     * @inheritDoc
     */
    public function generateEventOptionsForModel($additionalData = [], $addRequest = true)
    {

        $additionalData['loggedInUser'] =  $this->getLoggedInUser();
        return parent::generateEventOptionsForModel($additionalData, $addRequest); // TODO: Change the autogenerated stub
    }

}
