<?php


namespace App\Repositories;


use App\Repositories\Contracts\ResidentRepository;
use App\Repositories\Contracts\UserRepository;
use Illuminate\Support\Facades\DB;

class EloquentResidentRepository extends EloquentBaseRepository implements ResidentRepository
{
    /**
     * @inheritDoc
     */
    public function save(array $data): \ArrayAccess
    {

        DB::beginTransaction();

        $userRepository = app(UserRepository::class);
        $user = $userRepository->save(['email' => $data['contactEmail'], 'password' => 'password', 'roles.roleId' => 5, 'roles.propertyId' => $data['propertyId'] ]);

        $data['userId'] = $user->id;

        $resident = parent::save($data); // TODO: Change the autogenerated stub

        DB::commit();

        return $resident;

    }
}
